
FROM ubuntu:jammy AS visqol-build
LABEL org.opencontainers.image.title="webrtcperf-visqol"
LABEL org.opencontainers.image.description="Visqol build."
LABEL org.opencontainers.image.source="https://github.com/vpalmisano/webrtcperf"
LABEL org.opencontainers.image.authors="Vittorio Palmisano <vpalmisano@gmail.com>"

ARG TARGETPLATFORM
ENV BAZEL_VERSION=5.3.2
RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        git \
        ninja-build \
        python3 \
        python3-pip \
        build-essential \
        python3-numpy \
    && if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        BAZEL_ARCH=arm64; \
    else \
        BAZEL_ARCH=x86_64; \
    fi \
    && curl -fsSL -o /usr/local/bin/bazel-${BAZEL_VERSION} \
        "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-linux-${BAZEL_ARCH}" \
    && chmod +x /usr/local/bin/bazel-${BAZEL_VERSION}
RUN \
    mkdir -p /src \
    && cd /src \
    && git clone --depth 1 https://github.com/aadilghani1/visqol
RUN cd /src/visqol \
    && bazel-${BAZEL_VERSION} build :visqol -c opt
