{
 "title": "Medianode",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Mediasoup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mediasoup workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"mediasoup.*\"}[1m])*100",
     "legendFormat": "{{mode}} cpu"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"mediasoup.*\"}[1m]))*100",
     "legendFormat": "system + user"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rtc_server_mediasoup_producers", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "Consumer Spatial layers",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtc_server_media_spatial_ratio_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rtc_server_mediasoup_consumers", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "Consumer Temporal layers",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtc_server_media_temporal_ratio_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Average Audio Bitrate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(rtc_server_media_bitrate_sum{client=\"producer\",kind=\"audio\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=\"producer\",kind=\"audio\",origin=\"server\"}[2m])",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_bitrate_sum{client=~\"[pP]roducer\",kind=\"audio\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=~\"[pP]roducer\",kind=\"audio\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Average Audio Jitter",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(rtc_server_media_jitter_sum{client=\"producer\",kind=\"audio\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_jitter_count{client=\"producer\",kind=\"audio\",origin=\"server\"}[2m])",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_jitter_sum{client=~\"[pP]roducer\",kind=\"audio\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_jitter_count{client=~\"[pP]roducer\",kind=\"audio\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Total Audio Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(rtc_server_media_packet_count{kind=\"audio\",client=\"producer\",origin=\"server\"}[2m])",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_packet_count{kind=\"audio\",client=\"producer\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Total Audio Bitrate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "8 * rate(rtc_server_media_byte_count{kind=\"audio\",client=\"producer\",origin=\"server\"}[2m])",
       "legendFormat": "server"
      },
      {
       "expr": "8 * rate(rtc_server_media_byte_count{kind=\"audio\",client=\"producer\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Average Video Bitrate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(rtc_server_media_bitrate_sum{client=\"producer\",kind=\"video\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=\"producer\",kind=\"video\",origin=\"server\"}[2m]))",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_bitrate_sum{client=~\"[pP]roducer\",kind=\"video\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=~\"[pP]roducer\",kind=\"video\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Average Video Jitter",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(rtc_server_media_jitter_sum{client=\"producer\",kind=\"video\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_jitter_count{client=\"producer\",kind=\"video\",origin=\"server\"}[2m]))",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_jitter_sum{client=~\"[pP]roducer\",kind=\"video\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_jitter_count{client=~\"[pP]roducer\",kind=\"video\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Total Video Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(rtc_server_media_packet_count{kind=\"video\",client=\"producer\",origin=\"server\"}[2m]))",
       "legendFormat": "server"
      },
      {
       "expr": "rate(rtc_server_media_packet_count{kind=\"video\",client=\"producer\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    },
    {
     "title": "Producer Total Video Bitrate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(8 * rate(rtc_server_media_byte_count{kind=\"video\",client=\"producer\",origin=\"server\"}[2m]))",
       "legendFormat": "server"
      },
      {
       "expr": "8 * rate(rtc_server_media_byte_count{kind=\"video\",client=\"producer\",origin=\"client\"}[2m])",
       "legendFormat": "client"
      }
     ]
    }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Consumer Average Audio Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_bitrate_sum{client=\"consumer\",kind=\"audio\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=\"consumer\",kind=\"audio\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    },
    {
     "expr": "rate(rtc_server_media_bitrate_sum{client=~\"[cC]onsumer\",kind=\"audio\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=~\"[cC]onsumer\",kind=\"audio\",origin=\"client\"}[2m])",
     "legendFormat": "client"
    }
   ]
  },
  {
   "title": "Consumer Average Audio Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_jitter_sum{client=~\"[cC]onsumer\",kind=\"audio\",origin=\"client\"}[1m]) \n/ rate(rtc_server_media_jitter_count{client=~\"[cC]onsumer\",kind=\"audio\",origin=\"client\"}[1m])",
     "legendFormat": "client"
    }
   ]
  },
  {
   "title": "Consumer Total Audio Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_packet_count{kind=\"audio\",client=\"consumer\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Consumer Total Audio Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(rtc_server_media_byte_count{kind=\"audio\",client=\"consumer\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    },
    {
     "expr": "8 * rate(rtc_server_media_byte_count{kind=\"audio\",client=\"consumer\",origin=\"client\"}[2m])",
     "legendFormat": "client"
    }
   ]
  },
  {
   "title": "Consumer Average Video Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_bitrate_sum{client=\"consumer\",kind=\"video\",origin=\"server\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=\"consumer\",kind=\"video\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    },
    {
     "expr": "rate(rtc_server_media_bitrate_sum{client=~\"[cC]onsumer\",kind=\"video\",origin=\"client\"}[2m]) \n/ rate(rtc_server_media_bitrate_count{client=~\"[cC]onsumer\",kind=\"video\",origin=\"client\"}[2m])",
     "legendFormat": "client"
    }
   ]
  },
  {
   "title": "Consumer Average Video Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_jitter_sum{client=\"consumer\",kind=\"video\",origin=\"server\"}[1m]) \n/ rate(rtc_server_media_jitter_count{client=\"consumer\",kind=\"video\",origin=\"server\"}[1m])",
     "legendFormat": "server"
    },
    {
     "expr": "rate(rtc_server_media_jitter_sum{client=~\"[cC]onsumer\",kind=\"video\",origin=\"client\"}[1m]) \n/ rate(rtc_server_media_jitter_count{client=~\"[cC]onsumer\",kind=\"video\",origin=\"client\"}[1m])",
     "legendFormat": "client"
    }
   ]
  },
  {
   "title": "Consumer Total Video Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(rtc_server_media_packet_count{kind=\"video\",client=\"consumer\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Consumer Total Video Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(rtc_server_media_byte_count{kind=\"video\",client=\"consumer\",origin=\"server\"}[2m])",
     "legendFormat": "server"
    }
   ]
  }
 ]
}