{
 "title": "Webrtc Stress Test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "jobName", "label": "Job name", "query": { "query": "wst_cpu_max" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wst_cpu_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "wst_memory_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wst_cpu_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_cpu_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_cpu_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "wst_memory_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_memory_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_memory_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Tabs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wst_tabs_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Inbound audio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_audioBytesReceived_sum{job=\"$jobName\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "wst_audioRecvBitrates_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Packet Lost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wst_audioPacketsLost_mean{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wst_audioJitter_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_audioJitter_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_audioJitter_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Avg Jitter Buffer Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "wst_audioAvgJitterBufferDelay_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_audioAvgJitterBufferDelay_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_audioAvgJitterBufferDelay_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Inbound video", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_videoBytesReceived_sum{job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "wst_videoRecvBitrates_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Packet Lost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wst_videoPacketsLost_mean{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wst_videoJitter_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoJitter_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoJitter_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Avg Jitter Buffer Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "wst_videoAvgJitterBufferDelay_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoAvgJitterBufferDelay_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoAvgJitterBufferDelay_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Width",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "wst_videoFrameWidth_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "wst_videoFrameHeight_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Outbound audio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_audioBytesSent_sum{job=\"$jobName\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "wst_audioSendBitrates_sum{job=\"$jobName\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Retransmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_audioRetransmittedBytesSent_sum{job=\"$jobName\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Outbound video", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_videoBytesSent_sum{job=\"$jobName\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "wst_videoSendBitrates_sum{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoSendBitrates_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoSendBitrates_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Quality limit resolution changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wst_qualityLimitationResolutionChanges_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_qualityLimitationResolutionChanges_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_qualityLimitationResolutionChanges_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Width",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "wst_videoSourceWidth_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoSourceWidth_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoSourceWidth_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "wst_videoSourceHeight_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoSourceHeight_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoSourceHeight_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Framerate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wst_videoSourceFps_mean{job=\"$jobName\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "wst_videoSourceFps_min{job=\"$jobName\"}",
     "legendFormat": "min"
    },
    {
     "expr": "wst_videoSourceFps_max{job=\"$jobName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Retransmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wst_videoRetransmittedBytesSent_sum{job=\"$jobName\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}