name: Build release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    - name: Cache modules
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('./yarn.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ hashFiles('./yarn.lock') }}-
    - name: Install and build
      run: |
        yarn install --frozen-lockfile --network-timeout 60000 --network-concurrency 1
        yarn build
    - name: Publish to npm
      run: npm publish --access public --provenance
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
